en_US = {
    # offline screen
    'advice1': 'Unable to connect to server',
    'advice2': 'Try again later',
    # update screen
    'version': 'New version available',
    'download': 'Download',
    'wait1': 'Downloading.',
    'wait2': 'Downloading..',
    'wait3': 'Downloading...',
    # login screen
    'instruction1': 'Choose a nickname',
    'instruction2': '(It will appear in the rank)',
    'instruction3': 'Just letters and numbers',
    'confirm': 'Confirm',
    'warning1': 'Invalid nickname',
    'warning2': 'Nickname already in use',
    # menu screen
    'button_play': 'Play',
    'button_rank': 'Rank',
    'button_options': 'Options',
    'button_credits': 'Credits',
    'button_quit': 'Quit',
    'button_start': 'Start',
    'button_back': 'Back',
    'button_language': 'Language',
    'button_sound': 'Sound',
    'button_musics': 'Musics',
    'button_effects': 'Effects',
    'weapon': 'Choose a weapon:',
    'lock_ship_2': 'Survive 3 minutes',
    # credits screen
    'credits1': 'An indie game by',
    'credits2': 'Sounds',
    'credits3': 'Font',
    # rank screen
    'pos': 'Position',
    'nickname': 'Nickname',
    'score': 'Time',
    # level screen
    'control1': 'Dodge',
    'control2': 'Accelerate',
    'control3': 'Boost',
    'mouse1': 'Aim',
    'mouse2': 'Fire',
    'continue': 'Continue',
    'resume': 'Resume',
    'skip_song': 'Skip song',
    'skip_lvl': 'Skip',
    # cards screen
    'attack': 'Attack',
    'defense': 'Defense',
    'hp': 'Vitality',
    'hp_description': 'Increases your maximum health by 20%',
    'hp_special': 'Immortality',
    'hp_special_description': 'Regenerates 0.1% of your maximum health every second',
    'stamina': 'Agility',
    'stamina_description': 'Increases your maximum energy by 20%',
    'stamina_special': 'Force',
    'stamina_special_description': 'Doubles energy regeneration and halves consumption',
    'dodge': 'Wit',
    'dodge_description': 'Decreases dodge cooldown by 1 second',
    'dodge_special': 'Temporality',
    'dodge_special_description': 'Upon every 4 dodges, briefly freeze your enemies',
    'resurrection': 'Renaissance',
    'resurrection_description': 'When dying for the first time, resurrects with a percentage of maximum life. The percentage increases by 5% per level',
    'resurrection_special': 'Sacrifice',
    'resurrection_special_description': 'When dying for the second time, resurrects once more, this time creating a massive explosion of light that damages all enemies.',
    'shield': 'Protection',
    'shield_description': 'Generates a shield every 40 seconds. Decreases cooldown by 2.5 seconds per level',
    'shield_special': 'Steadfast',
    'shield_special_description': 'Shields withstand 3 instances of damage before breaking',
    'penetration': 'Penetration',
    'penetration_description': 'Shots pierce through an additional ship. Subsequent enemies hit after the first take 50% of the total damage',
    'penetration_special': 'Piercing',
    'penetration_special_description': 'Shots inflict full damage on all enemies they hit',
    'atkDMG': 'Wrath',
    'atkDMG_description': 'Increases your damage by 15%',
    'atkDMG_special': 'Vampirism',
    'atkDMG_special_description': 'Heals 2% of the damage caused by your shots',
    'atkSPD': 'Agitation',
    'atkSPD_description': 'Increases your attack speed by 15%',
    'atkSPD_special': 'Frenzy',
    'atkSPD_special_description': 'After not attacking for 5 seconds, gains a massive increase in attack speed for the same period',
    'ignite': 'Combustion',
    'ignite_description': 'Shots ignite enemies, dealing damage based on a percentage of their current health. Increases this damage by 10% per level',
    'ignite_special': 'Sadism',
    'ignite_special_description': 'Doubles the damage of over-time effects',
    'explosion': 'Destruction',
    'explosion_description': 'When destroying a ship, it creates a shockwave. Increases the radius by 25%',
    'explosion_special': 'Annihilation',
    'explosion_special_description': "The shockwave corrupts enemy ships, damaging them for 40% of their current health as damage over time",
    # dead screen
    'deadmessage1': 'You failed',
    'deadmessage2': 'just like the others...'
}

pt_BR = {
    # offline screen
    'advice1': 'Não foi possível conectar-se com o servidor',
    'advice2': 'Tente novamente mais tarde',
    # update screen
    'version': 'Nova versão disponível',
    'download': 'Baixar',
    'wait1': 'Baixando.',
    'wait2': 'Baixando..',
    'wait3': 'Baixando...',
    # login screen
    'instruction1': 'Escolha um apelido',
    'instruction2': '(Ele aparecerá na classificação)',
    'instruction3': 'Apenas letras e números',
    'confirm': 'Confirmar',
    'warning1': 'Apelido inválido',
    'warning2': 'Apelido já em uso',
    # menu screen
    'button_play': 'Jogar',
    'button_rank': 'Ranque',
    'button_options': 'Opções',
    'button_credits': 'Créditos',
    'button_quit': 'Sair',
    'button_start': 'Iniciar',
    'button_back': 'Voltar',
    'button_language': 'Idioma',
    'button_sound': 'Som',
    'button_musics': 'Músicas',
    'button_effects': 'Efeitos',
    'weapon': 'Escolha uma arma:',
    'lock_ship_2': 'Sobreviva 3 minutos',
    # credits screen
    'credits1': 'Um jogo independente por',
    'credits2': 'Sons',
    'credits3': 'Fonte',
    # rank screen
    'pos': 'Posição',
    'nickname': 'Apelido',
    'score': 'Tempo',
    # level screen
    'control1': 'Esquivar',
    'control2': 'Acelerar',
    'control3': 'Impulsionar',
    'mouse1': 'Mirar',
    'mouse2': 'Atirar',
    'continue': 'Continuar',
    'resume': 'Retomar',
    'skip_song': 'Pular música',
    'skip_lvl': 'Pular',
    # cards screen
    'attack': 'Ataque',
    'defense': 'Defesa',
    'hp': 'Vitalidade',
    'hp_description': 'Aumenta sua vida máxima em 20%',
    'hp_special': 'Imortalidade',
    'hp_special_description': 'Regenera 0.1% de sua vida máxima cada segundo',
    'stamina': 'Agilidade',
    'stamina_description': 'Aumenta sua energia máxima em 20%',
    'stamina_special': 'Potência',
    'stamina_special_description': 'Dobra a regeneração de energia e reduz pela metade o consumo',
    'dodge': 'Sagacidade',
    'dodge_description': 'Reduz a recarga da esquiva em 1 segundo',
    'dodge_special': 'Controle',
    'dodge_special_description': 'A cada 4 esquivas, congele brevemente seus inimigos',
    'resurrection': 'Renascença',
    'resurrection_description': 'Ao morrer pela primeira vez, ressuscita com um porcentagem da vida máxima. A porcentagem aumenta em 5% por nível',
    'resurrection_special': 'Sacrifício',
    'resurrection_special_description': 'Ao morrer pela segunda vez, ressuscita novamente, desta vez criando uma imensa explosão de luz que fere todos os inimigos',
    'shield': 'Proteção',
    'shield_description': 'Gera um escudo a cada 40 segundos. Reduz a recarga em 2.5 segundos por nível',
    'shield_special': 'Inabalável',
    'shield_special_description': 'Escudos suportam 3 instâncias de dano antes de se quebrarem',
    'penetration': 'Penetração',
    'penetration_description': 'Disparos atravessam uma nave adicional. Inimigos atingidos após o primeiro sofrem 50% do dano total',
    'penetration_special': 'Perfuração',
    'penetration_special_description': 'Disparos causam o dano total a todos os inimigos atingidos',
    'atkDMG': 'Ira',
    'atkDMG_description': 'Aumenta seu dano em 15%',
    'atkDMG_special': 'Vampirismo',
    'atkDMG_special_description': 'Cura-se em 2% do dano causado pelos seus disparos',
    'atkSPD': 'Agitação',
    'atkSPD_description': 'Aumenta sua velocidade de ataque em 15%',
    'atkSPD_special': 'Frenesi',
    'atkSPD_special_description': 'Ao não atacar por 5 segundos, ganha um imenso aumento de velocidade de ataque durante um período',
    'ignite': 'Combustão',
    'ignite_description': 'Disparos incendeiam os inimigos, ferindo-os em uma porcentagem de suas vidas atuais. Aumenta esse dano em 10% por nível',
    'ignite_special': 'Sadismo',
    'ignite_special_description': 'Dobra o dano de efeitos ao longo do tempo',
    'explosion': 'Destruição',
    'explosion_description': 'Ao destruir uma nave, cria uma onda de choque. Aumenta o raio da explosão em 25%',
    'explosion_special': 'Aniquilação',
    'explosion_special_description': 'A onda de choque corrompe as naves inimigas, danificando-os em 40% de suas vidas atuais como dano ao longo do tempo',
    # dead screen
    'deadmessage1': 'Você falhou',
    'deadmessage2': 'tais como os outros...'

}
